name: Read grant file
author: mmagician
description: 'Read file contents'
inputs:
  path:
    description: 'File path'
    required: true
  strict:
    description: 'Strict mode: fails instead of warning'
    required: false
    default: 'true'
outputs:
  team_name:
    description: 'Team name'
  level:
    description: 'Grant level'
  contact_name:
    description: 'Contact name'
  contact_email:
    description: 'Contact email'
  project_name:
    description: 'Project name'
  address:
    description: 'Registered address of legal entity'
  total_cost_dai:
    description: 'Total cost, DAI'
  total_milestones:
    description: 'Total number of milestones'
  is_maintenance:
    description: 'Is maintenance grant'
runs:
  using: 'node20'
  main: 'dist/index.js'
